### ISSUE TITLE
Headings of sections

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat-guidelines#12]
Currently in Muscat the headings for the sections look like this:
![grafik](https://user-images.githubusercontent.com/18663291/143284851-8f7ce9b7-f718-4e75-a5b9-b9975c7b7d8b.png)

The "Cataloging musical sources", "Library information", and "Library siglum" come from elsewhere, not from my md files. Can we create a way for these section titles to be in the md files somewhere? Maybe either in the file itself or (having in mind #10 ) in a separate md file?

Putting the section titles in the md document would give me more control over formatting and names of sections, several of which I would like to change or edit as I go, and creating a separate md file would allowed untranslated sections of the guidelines to have a translated heading but shared guidelines (if that makes sense).

**Comment by lpugin** [comment]
We need to think about it. Currently, the overall structure of the guidelines is given here
https://github.com/rism-digital/muscat-guidelines/blob/main/default/guidelines.yml
We can probably put most of the titles of the sections within the text .md files. We will still need a way to represent the structure and that will have to include the chapter titles, which will not be in the text .md files.

**Comment by jenniferward** [comment]
New ticket for new website will follow.
