### ISSUE TITLE
Header of Guidelines page

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat-guidelines#47]
- [x] Muscat logo should be replaced by the RISM logo. The Muscat logo can go somewhere else, but not in a place that is so prominent
- [x] The title should be `RISM Cataloging Guidelines`
- [x] The 2nd link goes to the Muscat program, which is useful for catalogers but not for members of the public. Maybe remove it entirely? 

I'm happy to link to http://muscat-project.org/ elsewhere on the Introduction page. Maybe later we can find a spot for Muscat login.

**Comment by lpugin** [comment]
See https://github.com/rism-digital/muscat-guidelines-site/pull/3
